# Pure MCL generator from our IR (files-only PoC).
# Usage: (import ./codegen/mcl-from-ir.nix { inherit lib; })(filesIR)
{ lib }:
let
  nl = "\n";
  esc = s: lib.replaceStrings [ "\\" "\"" ] [ "\\\\" "\\\"" ] (toString s);

  renderFile = import ./file.nix { inherit esc; };
in
filesIR:
  let
    header = ''
      # AUTOGENERATED by rx.nix (files-only PoC)
      # Input: manifest.json
    '';
    body =
      lib.concatMapStrings (f: renderFile f + nl)
        (filesIR.files or []);
  in
  header + nl + body
